# Numpy practice for data analysis: numpy test, arrays, operations
### Numpy test; Numpy Introduction B

In [89]:
import numpy as np

In [90]:
n = 3 

In [91]:
2 ** n

8

### Numpy Arrays
Basic Numpy Arrays

In [92]:
# IMport the necessary libraries
import sys
import numpy as np

In [93]:
np.array([1, 2, 3, 4, 5])  # Example of creating a numpy array

array([1, 2, 3, 4, 5])

In [94]:
a = np.array([1, 2, 3, 4, 5]) #

Variation 1 of muti-indexing using 1

In [95]:
b = np.array([0, -5, 1, 1.5, 2])

In [96]:
a[0], a[1]  # Accessing elements of the array

(np.int64(1), np.int64(2))

In [97]:
b

array([ 0. , -5. ,  1. ,  1.5,  2. ])

In [98]:
a

array([1, 2, 3, 4, 5])

### This is an example of multi-indexing 2d numpy arrays

In [99]:
c = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])  # Example of a 2D numpy array

In [100]:
# You can access elements using multi-indexing
element = c[1, 2]  # Accessing the element at row 1
# and column 2 (which is 6 in this case)

In [101]:
print(element)  # Output: 6

6


###  Array types

In [102]:
a

array([1, 2, 3, 4, 5])

In [103]:
# using the .dtype method to check the data type of the array
print(a.dtype)  # Output: int64 (or similar, depending on your system)

int64


In [104]:
# or
a.dtype  # This will also show the data type of the array 

dtype('int64')

In [105]:
print(b.dtype)  # Output: float64 (since b contains a float)

float64


In [106]:
# you can change the array's data type 
a = a.astype(float)  # Convert to float type
print(a.dtype)  # Output: float64
print(a)  # Output: [1. 2. 3. 4. 5.]

float64
[1. 2. 3. 4. 5.]


In [107]:
# you can chang the data type of the array into a smaller data type 
# for better memory usage
a = a.astype(np.int8)  # Convert to int8 type
print(a.dtype)  # Output: int8
print(a)  # Output: [1 2 3 4 5]

int8
[1 2 3 4 5]


### Dimensions and shapes

In [108]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [109]:
# shape of the array
A.shape

(3, 3)

In [110]:
A.ndim  # Number of dimensions (2 in this case)

2

In [111]:
A.size  # Total number of elements in the array (9 in this case)

9

In [112]:
# 3d array
B = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])  # Example of a 3D numpy array

In [113]:
B

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [114]:
B.shape  # Shape of the 3D array

(2, 2, 2)

In [115]:
B.ndim  # Number of dimensions (3 in this case)

3

In [116]:
B.size  # Total number of elements in the 3D array (8 in this case)

8

You can create a wrong multidimentional array

In [117]:
#C = np.array([[[1, 2], [3, 4]], [[5, 6]]])  

In [118]:
#C.dtype  # This will raise an error because the array is not well-formed

### Indexing and slicing of matrices

In [119]:
# square matrix
# This is an example of multi-indexing 3d numpy arrays
D = np.array([[ # Example of a 3D numpy array
            #   0, 1, 2 
               [0, 1, 2], # 0
               [3, 4, 5], # 1
               [6, 7, 8] # 2
               ],])
           

In [120]:
# Getting the 1st element of the 1st row
D[0, 0]  # Output: 0

array([0, 1, 2])

In [121]:
D[0]  # Accessing elements using multi-indexing

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [122]:
 # Question
A = np.array([
    ['a', 'b', 'c'],
    ['d', 'e', 'f'],
    ['g', 'h', 'i']
])

print(A[:, :2])

[['a' 'b']
 ['d' 'e']
 ['g' 'h']]


### Numpy Operations
Broadcasting and vectorizing operations in numpy


In [123]:
a = np.arange(4)  # This will create an array with values from 0 to 3

In [124]:
a

array([0, 1, 2, 3])

In [125]:
# Vectorizing operations involves performing operations on entire arrays. Example:
a + 10

array([10, 11, 12, 13])

The + 10 was added to each single value of the array 

In [126]:
 a * 10

array([ 0, 10, 20, 30])

The operation of the named array is vectorized then broadcasted to each element of the named array. The result is a new named array with the same structure as the original. Essentialy creating a new array and returning it.

In [127]:
a

array([0, 1, 2, 3])

In [128]:
a += 100

In [129]:
a

array([100, 101, 102, 103])

In [130]:
a = np.arange(4)  # Re-creating the array with values from 0 to 3

In [131]:
a

array([0, 1, 2, 3])