# Numpy practice

In [1]:
import numpy as np

In [2]:
n = 3 

In [3]:
2 ** n

8

Basic Numpy Arrays

In [4]:
# IMport the necessary libraries
import sys
import numpy as np

In [5]:
np.array([1, 2, 3, 4, 5])  # Example of creating a numpy array

array([1, 2, 3, 4, 5])

In [6]:
a = np.array([1, 2, 3, 4, 5]) #

Variation 1 of muti-indexing using 1

In [7]:
b = np.array([0, -5, 1, 1.5, 2])

In [8]:
a[0], a[1]  # Accessing elements of the array

(np.int64(1), np.int64(2))

In [9]:
b

array([ 0. , -5. ,  1. ,  1.5,  2. ])

In [10]:
a

array([1, 2, 3, 4, 5])

### This is an example of multi-indexing 2d numpy arrays

In [11]:
c = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])  # Example of a 2D numpy array

In [12]:
# You can access elements using multi-indexing
element = c[1, 2]  # Accessing the element at row 1
# and column 2 (which is 6 in this case)

In [13]:
print(element)  # Output: 6

6


###  Array types

In [14]:
a

array([1, 2, 3, 4, 5])

In [15]:
# using the .dtype method to check the data type of the array
print(a.dtype)  # Output: int64 (or similar, depending on your system)

int64


In [16]:
# or
a.dtype  # This will also show the data type of the array 

dtype('int64')

In [17]:
print(b.dtype)  # Output: float64 (since b contains a float)

float64


In [18]:
# you can change the array's data type 
a = a.astype(float)  # Convert to float type
print(a.dtype)  # Output: float64
print(a)  # Output: [1. 2. 3. 4. 5.]

float64
[1. 2. 3. 4. 5.]


In [19]:
# you can chang the data type of the array into a smaller data type 
# for better memory usage
a = a.astype(np.int8)  # Convert to int8 type
print(a.dtype)  # Output: int8
print(a)  # Output: [1 2 3 4 5]

int8
[1 2 3 4 5]


### Dimensions and shapes

In [20]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [21]:
# shape of the array
A.shape

(3, 3)

In [22]:
A.ndim  # Number of dimensions (2 in this case)

2

In [23]:
A.size  # Total number of elements in the array (9 in this case)

9

In [24]:
# 3d array
B = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])  # Example of a 3D numpy array

In [25]:
B

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [26]:
B.shape  # Shape of the 3D array

(2, 2, 2)

In [27]:
B.ndim  # Number of dimensions (3 in this case)

3

In [28]:
B.size  # Total number of elements in the 3D array (8 in this case)

8

You can create a wrong multidimentional array

In [29]:
#C = np.array([[[1, 2], [3, 4]], [[5, 6]]])  

In [30]:
#C.dtype  # This will raise an error because the array is not well-formed

### Indexing and slicing of matrices

In [31]:
# square matrix
# This is an example of multi-indexing 3d numpy arrays
D = np.array([[ # Example of a 3D numpy array
            #   0, 1, 2 
               [0, 1, 2], # 0
               [3, 4, 5], # 1
               [6, 7, 8] # 2
               ],])
           

In [32]:
# Getting the 1st element of the 1st row
D[0, 0]  # Output: 0

array([0, 1, 2])

In [33]:
D[0]  # Accessing elements using multi-indexing

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [34]:
 # Question
A = np.array([
    ['a', 'b', 'c'],
    ['d', 'e', 'f'],
    ['g', 'h', 'i']
])

print(A[:, :2])

[['a' 'b']
 ['d' 'e']
 ['g' 'h']]
