# Numpy practice for data analysis: numpy test, arrays, operations
### Numpy test; Numpy Introduction B

In [1]:
# IMport the necessary libraries
import sys
import numpy as np

In [2]:
n = 3 

In [3]:
2 ** n

8

### Numpy Arrays
Basic Numpy Arrays

In [4]:
np.array([1, 2, 3, 4, 5])  # Example of creating a numpy array

array([1, 2, 3, 4, 5])

In [5]:
a = np.array([1, 2, 3, 4, 5]) #

Variation 1 of muti-indexing using 1

In [6]:
b = np.array([0, -5, 1, 1.5, 2])

In [7]:
a[0], a[1]  # Accessing elements of the array

(np.int64(1), np.int64(2))

In [8]:
b

array([ 0. , -5. ,  1. ,  1.5,  2. ])

In [9]:
a

array([1, 2, 3, 4, 5])

### This is an example of multi-indexing 2d numpy arrays

In [10]:
c = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])  # Example of a 2D numpy array

In [11]:
# You can access elements using multi-indexing
element = c[1, 2]  # Accessing the element at row 1
# and column 2 (which is 6 in this case)

In [12]:
print(element)  # Output: 6

6


###  Array types

In [13]:
a

array([1, 2, 3, 4, 5])

In [14]:
# using the .dtype method to check the data type of the array
print(a.dtype)  # Output: int64 (or similar, depending on your system)

int64


In [15]:
# or
a.dtype  # This will also show the data type of the array 

dtype('int64')

In [16]:
print(b.dtype)  # Output: float64 (since b contains a float)

float64


In [17]:
# you can change the array's data type 
a = a.astype(float)  # Convert to float type
print(a.dtype)  # Output: float64
print(a)  # Output: [1. 2. 3. 4. 5.]

float64
[1. 2. 3. 4. 5.]


In [18]:
# you can chang the data type of the array into a smaller data type 
# for better memory usage
a = a.astype(np.int8)  # Convert to int8 type
print(a.dtype)  # Output: int8
print(a)  # Output: [1 2 3 4 5]

int8
[1 2 3 4 5]


### Dimensions and shapes

In [19]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [20]:
# shape of the array
A.shape

(3, 3)

In [21]:
A.ndim  # Number of dimensions (2 in this case)

2

In [22]:
A.size  # Total number of elements in the array (9 in this case)

9

In [23]:
# 3d array
B = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])  # Example of a 3D numpy array

In [24]:
B

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [25]:
B.shape  # Shape of the 3D array

(2, 2, 2)

In [26]:
B.ndim  # Number of dimensions (3 in this case)

3

In [27]:
B.size  # Total number of elements in the 3D array (8 in this case)

8

You can create a wrong multidimentional array

In [28]:
#C = np.array([[[1, 2], [3, 4]], [[5, 6]]])  

In [29]:
#C.dtype  # This will raise an error because the array is not well-formed

### Indexing and slicing of matrices

In [30]:
# square matrix
# This is an example of multi-indexing 3d numpy arrays
D = np.array([[ # Example of a 3D numpy array
            #   0, 1, 2 
               [0, 1, 2], # 0
               [3, 4, 5], # 1
               [6, 7, 8] # 2
               ],])
           

In [31]:
# Getting the 1st element of the 1st row
D[0, 0]  # Output: 0

array([0, 1, 2])

In [32]:
D[0]  # Accessing elements using multi-indexing

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [33]:
 # Question
A = np.array([
    ['a', 'b', 'c'],
    ['d', 'e', 'f'],
    ['g', 'h', 'i']
])

print(A[:, :2])

[['a' 'b']
 ['d' 'e']
 ['g' 'h']]


### Numpy Operations
Broadcasting and vectorizing operations in numpy


In [34]:
a = np.arange(4)  # This will create an array with values from 0 to 3

In [35]:
a

array([0, 1, 2, 3])

In [36]:
# Vectorizing operations involves performing operations on entire arrays. Example:
a + 10

array([10, 11, 12, 13])

The + 10 was added to each single value of the array 

In [37]:
 a * 10

array([ 0, 10, 20, 30])

The operation of the named array is vectorized then broadcasted to each element of the named array. The result is a new named array with the same structure as the original. Essentialy creating a new array and returning it.

In [38]:
a

array([0, 1, 2, 3])

In [39]:
a += 100

In [40]:
a

array([100, 101, 102, 103])

In [41]:
a = np.arange(4)  # Re-creating the array with values from 0 to 3

In [42]:
a

array([0, 1, 2, 3])

In [43]:
# Exercise
a = np.arange(5)

In [44]:
a + 20


array([20, 21, 22, 23, 24])

In [45]:
a

array([0, 1, 2, 3, 4])

In [46]:
a = a + 20

In [47]:
a

array([20, 21, 22, 23, 24])

In [48]:
a

array([20, 21, 22, 23, 24])

### Numpy Boolean Arrays
(also called masks)

In [49]:
a = np.arange(4)  # Re-creating the array with values from 0 to 3

In [50]:
a

array([0, 1, 2, 3])

In [51]:
# In python, you can access elements of a numpy array using indexing. For example:
a[0], a[-1]

(np.int64(0), np.int64(3))

In [52]:
# Same as in numpy; multiindexing
a[[0, -1]]  # Accessing the first and last elements using a list of indices

array([0, 3])

In [53]:
# There is a third option of using a boolean mask
# to select the rows of the dataframe that meet the condition
# True if you want to select the elements, False if you want to skip them
a[[True, False, False, True]] # Example boolean mask

array([0, 3])

In [54]:
a <= 2  # Example of a boolean mask condition

array([ True,  True,  True, False])

In [55]:
a >= 2  # Example of a boolean mask condition

array([False, False,  True,  True])

In [56]:
# Advantage of boolean masks is that you can use them to filter the array based on conditions
a[a>=2]

array([2, 3])

In [57]:
a.mean()  # Calculate the mean of the array

np.float64(1.5)

In [58]:
# In numpy, you can also use boolean indexing to filter elements based on conditions and specific methods. For example:
a[a >= a.mean()]  # This will return elements greater than the mean of the array

array([2, 3])

In [59]:
a[a <= a.mean()] # This will return elements less than the mean of the array

array([0, 1])

 You can also include or[|] , and[$] operators in boolean masks

In [60]:
# or[|] operation
a[(a==0) | (a==1)]  # This will return elements that are either 0 or 1 in the array

array([0, 1])

In [61]:
# and [&] operation
a[(a<=2) & (a%2==0)]  # This will return elements that are less than or equal to 2 and even

array([0, 2])

In [62]:
A =np.random.randint(0, 10, size=(4, 4))  # Example of creating a random integer array

In [63]:
A

array([[7, 5, 9, 9],
       [1, 7, 1, 9],
       [4, 2, 8, 5],
       [9, 2, 9, 7]])

In [64]:
# Not normaly done but you can use boolean indexing with a boolean mask to select specific rows and columns
# Example of a boolean mask to select specific rows and columns
# This will return elements that match the boolean mask condition
A[np.array([
    [True, False, True, False], [True, True, True, False], [False, True, True, False], [True, True, False, False]] ) ] 

array([7, 9, 1, 7, 1, 2, 8, 9, 2])

In [65]:
# boolean indexing
A > 3

array([[ True,  True,  True,  True],
       [False,  True, False,  True],
       [ True, False,  True,  True],
       [ True, False,  True,  True]])

### Numpy Algebra and Size
Linear Algebra

#### Size of objects in memory
Int,floats

In [ ]:
# An integer in Python is > 24bytes
sys.getsizeof(1)  # Get the size of an integer in bytes

28

In [71]:
# Longs are even larger
sys.getsizeof(10**360)  # Get the size of a long integer in bytes

184

In [72]:
# Numpy size is much smaller
np.dtype(int).itemsize  # Get the size of an integer in bytes in numpy

8